name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: 
    steps:

      - run: |
          echo '::warning ${{toJson(github.event)}}'
          echo ${{toJson(github)}}
