name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - run: |
          #echo '::warning ${{toJson(github.event)}}'
          #echo '''${{toJson(github)}}'''
          echo URL: '''${{github.server_url}}/${{github.repository}}'''
